CREATE TABLE QUESTION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    QUESTION_TEXT VARCHAR(255),
    OPTION_A VARCHAR(255),
    OPTION_B VARCHAR(255),
    OPTION_C VARCHAR(255),
    OPTION_D VARCHAR(255),
    CORRECT_ANSWER VARCHAR(1)
);

CREATE TABLE QUIZ_SESSION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50),
    ANSWERED_QUESTIONS VARCHAR(255)
);

CREATE TABLE USER_STATS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50),
    TOTAL_ANSWERED INT,
    CORRECT_ANSWERS INT,
    INCORRECT_ANSWERS INT
);
